### ISSUE TITLE
incorrect placement in computed values  

### ISSUE THREAD

**Issue by der-ali** [1Password/connect-helm-charts#109]
### Your environment

Chart Version: 1.8.0

Helm Version: v3.9.0

Kubernetes Version: 1.21

## What happened?

I am using the chart as dependency in my helm chart. My helm chart includes the following Chart.yaml
```
apiVersion: v2
name: 1password-connect-local
description: A Helm chart for deploying 1Password Connect and the 1Password Connect Kubernetes Operator
type: application
version: 0.1.0

appVersion: "1.5.4"

dependencies:
- name: connect
  version: 1.8.0
  repository: https://1password.github.io/connect-helm-charts
```

If i execute :
```
helm dependency build .
helm -n 1password install mychart   --create-namespace --dry-run --debug .
```
i get the following computed values:
```
connect:
  acceptanceTests:
    enabled: false
    fixtures: {}
  annotations: {}
  api:
    httpPort: 8080
    httpsPort: 8443
    imageRepository: 1password/connect-api
    name: connect-api
    resources: {}
  applicationName: onepassword-connect
  connect:
    annotations: {}
    api:
      httpPort: 8080
      httpsPort: 8443
      imageRepository: 1password/connect-api
      name: connect-api
      resources: {}
    applicationName: onepassword-connect
    credentialsKey: 1password-credentials.json
    credentialsName: op-credentials
    dataVolume:
      name: shared-data
      type: emptyDir
      values: {}
    imagePullPolicy: IfNotPresent
    labels: {}
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
 ```
As you see the `connect` dictionary exists two times and  `AcceptanceTests` are under one of the connect dictionaries instead of root

**Comment by dustin-ruetz-1p** [comment]
Hi @der-ali - thank you for taking the time to file this issue.

After discussing this one internally with the team we noticed that there is an `api` block on the parent `connect` block as well, so it looks like a mix-up is occurring here somewhere. Is it possible that Helm or something in our chart doesn’t like the fact that there are two `connect` blocks, and it’s mixing them up? A potential workaround that we can suggest is for you to try using a different `name` under `dependencies`. (Caveat: we haven’t tested this ourselves.) For example:

```yaml
# Chart.yaml
dependencies:
- name: 1password-connect
```
