### ISSUE TITLE
SQLITE ERROR when using PVC

### ISSUE THREAD

**Issue by tomjohnburton** [1Password/connect-helm-charts#134]
### Your environment

Chart Version: 1.10.0

Helm Version: 3.10.1

Kubernetes Version: v1.23.9

## What happened?

I tried using the following to set up a PVC and attach it to 1password-connect pod so that 1password doesn't write the node (which btw was causing intermittent disk pressure warnings)

```yaml
# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onepassword-connect-shared-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```
```yaml
# values.yaml
connect:
  serviceType: ClusterIP
  dataVolume:
    type: persistentVolumeClaim
    values:
      claimName: onepassword-connect-shared-data
      readOnly: false
```

When the `connect-sync` container starts up I see the following:
```
{"log_message":"(I) disabling bus peer auto-discovery","timestamp":"2023-01-18T02:07:57.431543892Z","level":3}
{"log_message":"(W) did not initialize bus connection to peer localhost:11220. If the peer is currently booting, it may initialize the connection while starting. Details: failed to transport.CreateConnection: [transport-websocket] failed to Dial endpoint: dial tcp 127.0.0.1:11220: connect: connection refused. ","timestamp":"2023-01-18T02:07:57.435251551Z","level":2}
{"log_message":"(W) configured to use HTTP with no TLS","timestamp":"2023-01-18T02:07:57.435325947Z","level":2}
{"log_message":"(I) no existing database found, will initialize at /home/opuser/.op/data/1password.sqlite","timestamp":"2023-01-18T02:07:57.435664243Z","level":3}
Error: Server: (failed to OpenDefault), Wrapped: (failed to open db), unable to open database file: no such file or directory
Usage:
  connect-sync [flags]

Flags:
  -h, --help      help for connect-sync
  -v, --version   version for connect-sync
```

## What did you expect to happen?

1password starts up without issue

## Steps to reproduce
1.  Create a PVC
2. Attach it to the pod by setting the config as described above

**Comment by jillianwilson** [comment]
Hey there, thanks for sharing this issue. Could you provide some details around what K8s platform you are using so we can debug this further.

Also here are some things to double check:
- Double check that both pods have permissions to read and write to the PVC
- Permissions for the volume need to be set to match the non root permissions of the connect container

**Comment by edif2008** [comment]
Hey @tomjohnburton! 👋 

It's been a while since we've asked for clarification regarding this issue. Is this still an issue for your infrastructure?

**Comment by oed-grotel** [comment]
We encounter the same Issue switching from default emptyDir config to a RWX PVC when using more than 1 Replica.

PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onepassword-connect-shared-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
```

values.yaml:
```yaml
connect:
  dataVolume:
    type: "persistentVolumeClaim"
    values:
      claimName: "onepassword-connect-shared-data"
```

PVC access rights:
<img width="848" height="205" alt="Image" src="https://github.com/user-attachments/assets/39b748fc-5845-444f-bd34-7ac1eb17b538" />
