### ISSUE TITLE
Chart repo down

### ISSUE THREAD

**Issue by kreempuff** [1Password/connect-helm-charts#153]
### Your environment

Chart Version:

Helm Version:

Kubernetes Version:

## What happened?

```
Error: looks like "https://1password.github.io/connect-helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://1password.github.io/connect-helm-charts/index.yaml : 404 Not Found
```

## Steps to reproduce
1. helm repo add 1password https://1password.github.io/connect-helm-charts

**Comment by kreempuff** [comment]
Work around in my case is using the release directly within my [helmfile](https://github.com/helmfile/helmfile):
```yaml
- name: connect
    chart: https://github.com/1Password/connect-helm-charts/releases/download/connect-1.11.0/connect-1.11.0.tgz
    namespace: system-internal
    version: "~1.10.0"
    values:
      - 1p-connect.values.yaml
    secrets:
      - 1p-connect.secrets.yaml
```
