### ISSUE TITLE
Add ability to install custom CA certificates in the Operator

### ISSUE THREAD

**Issue by fzappia** [1Password/connect-helm-charts#171]
### Summary
Add ability to install custom CA certificates in the Operator. 

### Use cases
To enable TLS communication between the operator and the connect-api, a valid certificate needs to be provided. Currently, a self-signed certificate or a certificate signed by a custom CA will make the operator request fail.

Given the common use case of deploying the connect-api service in private networks, obtaining a valid certificate from a valid CA does not seem an achievable solution.

### Proposed solution
Add `volumeMounts` (and `volumes`) field to the specifications of the Operator. These fields are used to mount custom volumes into the Operator pod. E.g. 

```yaml
operator: 
  ...
  volumeMounts:
    - name: ca-vol
      mountPath: /usr/local/share/ca-certificates/
  volumes:
    - name: ca-vol
      configMap:
        name: ca-crt
```

Furthermore, the CA store needs to be updated at container boot (or provided the ability to do so)

### Is there a workaround to accomplish this today?
No.
