### ISSUE TITLE
Ingress resource is not created

### ISSUE THREAD

**Issue by Tipsmark** [1Password/connect-helm-charts#179]
### kubernetes

Chart Version: latest 1.8

Helm Version: latest

Kubernetes Version: 1.27, 1.28

## What happened?
ingress: true does NOTHING

## What did you expect to happen?
ingress resource to be created

## Steps to reproduce
deploy chart, modify ingress in values to true and configure the rest.

**Comment by ingridcrant** [comment]
Hi @Tipsmark 👋🏻 I'm actively looking into this issue. Could you provide the helm command that you're using alongside the config file (if any) you're passing in so I can better help?

**Comment by Tipsmark** [comment]
Sure, I use kustomization but you'll get the general idea. I need the patch to ensure the URL works.

kustomization.yaml
`apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: secrets-injector
  version: 1.0.1
  repo: https://1password.github.io/connect-helm-charts/
  releaseName: core
  
- name: connect
  version: "1.15"
  repo: "https://1password.github.io/connect-helm-charts/"
  namespace: 1password
  releaseName: core
  includeCRDs: true
  valuesInline:
    connect:
      credentials_base64: CI6dHJ1ZSwiayI6InJPTFR5c1dmNENsVXEyRDZUM0xYc19od3dDUjhObzhYNnJGR2U3UW1iT2MiLCJrZXlfb3BzIjpbImVuY3J5cHQiLCJkZWNyeXB0Il0sImt0eSI6Im9jdCIsImtpZCI6InVtN2x2eGV5Nnd0bmw0YTJpYW12bndoc2txIn19blahblahblah
    operator:
      create: true
      token:
        name: 1password-token
        key: token

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "https://<the url I actually want>"
    target:
      kind: Deployment
      name: onepassword-connect-operator

resources:
  - ingress.yaml
  - 1password-token.yaml`

ingress.yaml:

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 1password-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: <my url>
spec:
  ingressClassName: nginx-internal
  rules:
  - host: <my url>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onepassword-connect
            port:
              name: connect-api
  tls:
  - hosts:
    - <my url>
    secretName: 1password-tls`

**Comment by ingridcrant** [comment]
I haven't used kustomization with this helm chart before, but I spun up a crude version of it with our connect helm chart to demonstrate that an ingress resource is created. Here is what I have:

**kustomization.yaml**
```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: secrets-injector
    version: 1.0.1
    repo: https://1password.github.io/connect-helm-charts/
    releaseName: core

  - name: connect
    version: "1.15"
    repo: "https://1password.github.io/connect-helm-charts/"
    releaseName: core
    includeCRDs: true
    valuesInline:
      connect:
        credentials_base64: <my credentials>
        ingress:
          enabled: true
      operator:
        create: true
        token:
          value: <my token>
```

And here is how I deployed
![Screenshot 2024-05-14 at 4 15 44 PM](https://github.com/1Password/connect-helm-charts/assets/55631417/7ef5903f-0f41-4eea-8b42-baa1b17322e7)

**Comment by ingridcrant** [comment]
I believe that a good place to start is to make sure that those ingress values are passed in properly to the chart. From your **kustomization.yaml**, you're including `ingress.yaml` as a resource. If you're running `kustomize build` it's patching it into the bottom of your **kustomization.yaml** like this:
```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: secrets-injector
    version: 1.0.1
    repo: https://1password.github.io/connect-helm-charts/
    releaseName: core
...
------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 1password-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: the-dns-name-I-want
spec:
  ingressClassName: nginx-internal
  rules:
    host: the-dns-name-I-want
    http:
...
```

This won't work correctly with our Helm Chart as we create an ingress resource based on what is passed in as values (insight into how our ingress works in [ingress.yaml](https://github.com/1Password/connect-helm-charts/blob/main/charts/connect/templates/ingress.yaml)).

I hope this information is helpful.
