### ISSUE TITLE
Connect Health Check always fails on the first run

### ISSUE THREAD

**Issue by mrclrchtr** [1Password/connect-helm-charts#190]
### Your environment

Chart Version:
1.15.0

Helm Version:
v3.14.3

Kubernetes Version:
1.29

## What happened?
Fail:
```json
{
  "name": "1Password Connect API",
  "version": "1.7.2",
  "dependencies": [
    {
      "service": "sqlite",
      "status": "ACTIVE",
      "message": "Connected to /home/opuser/.op/data/1password.sqlite"
    },
    {
      "service": "account_data",
      "status": "NOT_SYNCED",
      "message": "Account data is not available because synchronization has not yet started"
    },
    {
      "service": "sync",
      "status": "TOKEN_NEEDED"
    },
    {
      "service": "1Password",
      "status": "UNINITIALIZED",
      "message": "Make a request with a valid bearer token to initialize"
    }
  ]
}
```

With the second apply it runs through successful.

## What did you expect to happen?
The first apply runs successfully.

## Steps to reproduce

Kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    releaseName: onepassword-connect
    namespace: vault
    version: 1.15.0
```

Command:
```bash
kubectl kustomize . --enable-helm | kubectl apply -f -
```

## Notes & Logs
After a while, it becomes successful on its own.
