### ISSUE TITLE
Upgrade from 1.8.1 to 1.9.0 / 1.17.1 to 2.0.0 breaks onepassword-connect-operator

### ISSUE THREAD

**Issue by kdambekalns** [1Password/connect-helm-charts#231]
### Your environment

Chart Version: 2.0.0

Helm Version: 3

Kubernetes Version: 1.32.5

## What happened?

The upgrade created a deployment that no longer has environment variables for

- `OP_CONNECT_HOST`
- `OP_CONNECT_TOKEN`

That results in

```
2025-06-30T18:12:39Z    ERROR    setup    unable to create 1Password client    {"error": "invalid configuration. Connect or Service Account credentials should be set"}
main.main
    /workspace/cmd/main.go:164
runtime.main
    /usr/local/go/src/runtime/proc.go:283
```

sending the pod into `CrashLoopBackOff`.

## What did you expect to happen?

An upgrade that just works… 😇

## Steps to reproduce

Well, have a running setup of chart version 1.17.1 and upgrade to chart 2.0.0. Our `HelmRelease` looks like this:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: 1password-connect
      version: '>=1.15.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: connect
  targetNamespace: 1password
  upgrade:
    crds: CreateReplace

  values:
    connect:
      create: true
      credentialsName: 1password-credentials
    operator:
      create: true
      token:
        name: 1password-token
```

## Notes & Logs

It seems https://github.com/1Password/connect-helm-charts/commit/9ce9b4d21a54f06eb9862ab1a5935b2693767056 is the cause – we don't have `operator.token.value` set for the check in line 82.

And since we have the secret already, I don't see why it would be needed. Also, in that if/else the value is not even used…

Plus, setting it would create the token (again) as per https://github.com/1Password/connect-helm-charts/blob/7310f4dd3a0c71fa87d086000880ca62fcf84d6e/charts/connect/templates/operator-token.yaml

Thanks for reading this far – let me know if this misses something or I am completely off track. 🫶

**Comment by volodymyrZotov** [comment]
@kdambekalns Thank you for raising this. Let me see what's going on there.

**Comment by volodymyrZotov** [comment]
@kdambekalns As a workaround for this, you can set `operator.token.value` to anything. With that it will be able to set Connect env vars.
```
    operator:
      create: true
      token:
        name: 1password-token
        value: "placeholder"  # Required to render OP_CONNECT_TOKEN and OP_CONNECT_HOST env vars
```

I've just tried it and it works for me.
Meanwhile, I'll work on the fix for that, as you fairly mention, providing `operator.token.value` should not be required when upgrading.
