### ISSUE TITLE
Using with Helm

### ISSUE THREAD

**Issue by nodesocket** [1Password/connect-helm-charts#39]
I am currently using standard Helm and a template like:

```
{{- $def := index .Values "default" -}}
apiVersion: v1
data:
  STRIPE_PUBLIC_KEY: {{ default $def.STRIPE_PUBLIC_KEY | b64enc }}
  STRIPE_SECRET_KEY: {{ default $def.STRIPE_SECRET_KEY | b64enc }}
  # .... etc ....
kind: Secret
metadata:
  name: api-env
type: Opaque
```

Then the deployment simply does:

```
envFrom:
- secretRef:
  name: api-env
```

Finally, in the `values.yaml` we specify the secrets like:

```
default:
  STRIPE_PUBLIC_KEY: foobar
  STRIPE_SECRET_KEY: secret-foobar
```

How would migrating to 1Password-operator in our Kubernetes cluster work?

**Comment by nodesocket** [comment]
@jillianwilson thanks for the reply. Doesn't the official helm chart create the cluster role, service account, and role binding? If not, I must have missed that in the documentation. Can you point me to it?

**Comment by florisvdg** [comment]
Yes, it does, but you have to explicitly enable it:
```yml
operator:
  create: true
  serviceAccount:
    create: true
  roleBinding:
    create: true
  clusterRole:
    create: true
```

In the next release, we'll make it [create the RBAC resources by default](https://github.com/1Password/connect-helm-charts/pull/37) so you'll only have to add `--set operator.create=true`.
